package com.resicore.modules.platform.enums;

public enum AuditLogAction {
    LOGIN,
    LOGOUT,
    SOCIETY_APPROVED,
    SOCIETY_REJECTED,
    SOCIETY_SUSPENDED,
    ADMIN_CREATED,
    ADMIN_UPDATED,
    ADMIN_DEACTIVATED,
    ROLE_CHANGED,
    SETTINGS_UPDATED,
    CONFIGURATION_CHANGED,
    CRITICAL_OPERATION,
    ANALYTICS_GENERATED,
    SOCIETY_ACTIVATED,
    SOCIETY_DEACTIVATED
}
